server:
  port: 8080

spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    cache-names: redisCache
    type: redis
  redis:
    port: 6379
    password: lims
    host: localhost
# spring security相关配置、 实际情况,不可能只有一个用户、都是数据库中取出用户和角色、
  security:
    user:
      name: luxf
      password: 123456
      roles: ROLE_ADMIN

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.luxf.mybatis.bootmybatisdemo.entity
  configuration:
    default-executor-type: SIMPLE
    cache-enabled: false
    aggressive-lazy-loading: true
    use-column-label: true
    lazy-loading-enabled: false
    use-generated-keys: false
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
    safe-row-bounds-enabled: false
    safe-result-handler-enabled: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    return-instance-for-empty-row: false
    use-actual-param-name: true
    local-cache-scope: statement

#showSql
logging:
  level:
    com:
      luxf: DEBUG

# Spring Security 加密盐
application:
  security:
    secret: salt